/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guıcoolness;

/**
 *
 * @author sen
 */
import controller.ConnectDB;
import controller.Login_Controller;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import model.Login_Model;
public class Login_jframe extends javax.swing.JFrame {
    
private Connection conn;
private ResultSet rst;
private PreparedStatement pst;

    public Login_jframe() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txUname = new javax.swing.JTextField();
        txPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SimSun", 1, 18), new java.awt.Color(102, 102, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txUname.setBackground(new java.awt.Color(240, 240, 240));
        txUname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(txUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 400, 30));

        txPass.setBackground(new java.awt.Color(240, 240, 240));
        txPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPassActionPerformed(evt);
            }
        });
        jPanel1.add(txPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 400, 30));

        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 36, -1, -1));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 112, -1, -1));

        btLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLogin.setForeground(new java.awt.Color(0, 102, 102));
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 400, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User_icon_BLACK-01.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPassActionPerformed
    }//GEN-LAST:event_txPassActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
      onLoginClick();
    }//GEN-LAST:event_btLoginActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txPass;
    private javax.swing.JTextField txUname;
    // End of variables declaration//GEN-END:variables

    private void onLoginClick()
    {
        String uname,pwd;
        boolean status=false;
        NewJFrame frame=new NewJFrame();
        
        uname=txUname.getText();
        pwd=String.valueOf(txPass.getPassword());
        
        Login_Model loginModel= new Login_Model();
        loginModel.setUname(uname);
        loginModel.setPass(pwd);

        
      Login_Controller model= new Login_Controller(conn);
         status= model.login(loginModel);
         
         if(status==true){
             JOptionPane.showMessageDialog(rootPane, "Succesfully", "Info", JOptionPane.INFORMATION_MESSAGE);
             frame.setVisible(true);
             this.dispose();
             
         }
         else if(txUname.getText().isEmpty() && String.valueOf(txPass.getPassword()).isEmpty()){
                               JOptionPane.showMessageDialog(rootPane, "Username and Password still empty", "Info", JOptionPane.INFORMATION_MESSAGE);

             
         }
         else if(txUname.getText().equals(""))
         {
                  JOptionPane.showMessageDialog(rootPane, "Username still empty", "Info", JOptionPane.INFORMATION_MESSAGE);
         }else if(String.valueOf(txPass.getPassword()).equals(""))
         {
                  JOptionPane.showMessageDialog(rootPane, "Password still empty", "Info", JOptionPane.INFORMATION_MESSAGE);
                  
         }
         else if (!txUname.getText().isEmpty()){
             isUsernameExist();
         }
         else if(!String.valueOf(txPass.getPassword()).isEmpty())
                 {
                     isPasswordExist(); 
                 }
         else{
               JOptionPane.showMessageDialog(rootPane, "Invalid Username and Password", "Info", JOptionPane.INFORMATION_MESSAGE);
             
         }
    
    
    }
    private boolean isUsernameExist() 
    {
                boolean status=false;

    try {
        String sql="SELECT username FROM tbLogin";
        pst=ConnectDB.getConnection().prepareStatement(sql);
        pst.setString(1, txUname.getText());
        rst=pst.executeQuery();
        
        if(rst.next())
        {
            status=true;
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Invalid Username");
        }
        rst.close();
    } catch (SQLException ex) {
        Logger.getLogger(Login_jframe.class.getName()).log(Level.SEVERE, null, ex);
    }
    return status;
    }
    private boolean isPasswordExist()
    {
        boolean status=false;
         try {
        String sql="SELECT password FROM tbLogin";
        pst=ConnectDB.getConnection().prepareStatement(sql);
        
        pst.setString(1, txPass.getPassword().toString());
        rst=pst.executeQuery();
        
        if(rst.next())
        {
            status=true;
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Invalid Password");
        }
        rst.close();
    } catch (SQLException ex) {
        Logger.getLogger(Login_jframe.class.getName()).log(Level.SEVERE, null, ex);
    }
        return status;
    }
    
}
